# Site settings
title: Bella Love's Blog
header-img: img/home-bg.jpg
email: talktobella@corgi.way
copyright_name: Bella's Humans
description: "All things bearful"
baseurl: ""
url: "http://yourdomain.com"
twitter_username:
github_username:
facebook_username: bella.love.988373
email_username: talktobella@corgi.way

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
